#!/bin/bash
# Add this to your $PATH. This can be used by invoking the `journal`
# command or with an interval-based approach using cron (or both).
# To setup a cron job for a 30 minute interval:
#
#   0-30 * * * * journal
# 
# Original idea from http://www.stochasticgeometry.ie/2012/11/23/vimwiki/

# Check for journal path as an argument, otherwise fallback to the
# predefined $JOURNAL env or the default
if [ ! -z "$1" ]; then
    JOURNAL="$1"
elif [ ! -n "$JOURNAL" ]; then
    JOURNAL="$HOME/.journal"
fi

# Add an timestamp entry to the file, but first check if the file ends with
# a newline file for proper spacing
# Reference: http://www.commandlinefu.com/commands/view/6440/function-to-check-whether-a-regular-file-ends-with-a-newline
if [[ -f "$JOURNAL" && -s "$JOURNAL" && ! -z $(tail -1 "$JOURNAL") ]]; then
    echo '' >> "$JOURNAL"
fi

echo -e "// $(date '+%Y-%m-%d @ %H:%M')\n\n" >> "$JOURNAL"

if [ ! -z `which mvim` ]; then
    EDITOR=mvim
elif [ ! -z `which gvim` ]; then
    EDITOR=gvim
else
    EDITOR=vim
fi

$EDITOR + -c "startinsert" "$JOURNAL"
