#!/bin/bash

# Check if the variable is empty and set it if so
if [ ! -n "$JOURNAL" ]
then
    JOURNAL="$HOME/Journal"
fi

# Define today's directory where the log and related files are stored
TODAYS_DIR="$JOURNAL/$(date '+%Y')/$(date '+%m')/$(date '+%d')"

# Define the main log file
LOGFILE="$TODAYS_DIR/log.md"

# Ensure the directory for this day is created
mkdir -p $TODAYS_DIR

# Add an timestamp entry to the file, but first check if the file ends with
# a newline file for proper spacing
# Reference: http://www.commandlinefu.com/commands/view/6440/function-to-check-whether-a-regular-file-ends-with-a-newline
if [[ -f "$LOGFILE" && -s "$LOGFILE" && ! -z $(tail -1 "$LOGFILE") ]]
then
    echo '' >> "$LOGFILE"
fi

echo -n -e "-[" `date '+%H:%M:%S'` " - " `hostname` " ]-\n\n\n" >> "$LOGFILE"

# Launch the editor to edit the logfile
$EDITOR "$LOGFILE"
